import assert from 'node:assert/strict';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createCodex } from '../dist/index.js';
import { createAesEncryption } from '../dist/adapters/storage.js';
import { createAuthHandler } from '../dist/adapters/http.js';
import { mountCodexAuth } from '../dist/ui/index.js';
const pkg=JSON.parse(await readFile('package.json','utf8'));
assert.equal(pkg.name,'@thezem/codex-capsule');
assert.equal(pkg.scripts.prepare,'npm run build');
assert.equal(typeof createCodex,'function'); assert.equal(typeof createAesEncryption,'function'); assert.equal(typeof createAuthHandler,'function'); assert.equal(typeof mountCodexAuth,'function');
const ui=await readFile('dist/ui/index.js','utf8');assert(!/from ['"](?:node:|ai|@ai-sdk|jose)/.test(ui));
execFileSync('node_modules/.bin/tsc',['--noEmit','--target','ES2022','--module','NodeNext','--moduleResolution','NodeNext','--strict','--skipLibCheck','examples/tools.ts','examples/backend.ts','examples/auth-ui.ts'],{stdio:'inherit'});
const packed=JSON.parse(execFileSync('npm',['pack','--dry-run','--ignore-scripts','--json'],{encoding:'utf8'}))[0];
assert(!packed.files.some(f=>/(?:node_modules|\.artifacts|\.env|private-accounts|\.pem|\.key)/.test(f.path)));
for(const file of ['dist/index.js','dist/index.d.ts','dist/ui/index.js','LICENSE','NOTICE','assets/wordmark.svg'])assert(packed.files.some(f=>f.path===file));
await mkdir('.artifacts',{recursive:true});
const report={package:pkg.name,version:pkg.version,prepare:true,exports:Object.keys(pkg.exports),packedFiles:packed.files.map(f=>f.path),credentialsPacked:false};
await writeFile('.artifacts/package.json',JSON.stringify(report,null,2));console.log(`Package verified: ${pkg.name}@${pkg.version}, ${packed.files.length} packed files.`);
